<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_History</name>
   <tag></tag>
   <elementGuidId>2ca40972-732a-43d6-8d5f-7139a2e15ac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > div.PsKE7e.r8s4j-R6PoUb.IKA38e.baH5ib.oNsfjf > div.I35ICb > a.aJHbb.dk90Ob.hDrhEe.HlqNPb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='yuynLe']/ul/li[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;History&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>682b5998-7ac5-41ea-93f9-155d951af7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aJHbb dk90Ob hDrhEe HlqNPb</value>
      <webElementGuid>e564e5d2-2c8e-4472-9748-971c0b8bfea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>QwLHlb</value>
      <webElementGuid>54a5d631-8629-4a27-bf76-ae5a5fae892a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>0be9a711-f5c2-46d5-a63a-45ce4dfcbe45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>287c8bba-4578-4033-bd9a-3e7d8bd265a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navtype</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>37c06750-c59f-4878-934a-c5fb37870e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/view/satisfies/history</value>
      <webElementGuid>99e78326-a2b8-45e5-a803-096542cfe53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/view/satisfies/history</value>
      <webElementGuid>b7d6eb88-598b-4a54-86eb-6759d33b6de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f18e34d5-be4e-4d0a-9d3f-9ecf9a7355bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b84f5c05-ef16-4bb5-9efd-1d421d5c1dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>History</value>
      <webElementGuid>84f6dbc7-4c1a-47da-b23e-f5ac8a1bc38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yuynLe&quot;)/ul[@class=&quot;jYxBte Fpy8Db&quot;]/li[2]/div[@class=&quot;PsKE7e r8s4j-R6PoUb IKA38e baH5ib oNsfjf&quot;]/div[@class=&quot;I35ICb&quot;]/a[@class=&quot;aJHbb dk90Ob hDrhEe HlqNPb&quot;]</value>
      <webElementGuid>bc8c2e66-a2b2-482b-805f-38281bf8c01e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='yuynLe']/ul/li[2]/div/div/a</value>
      <webElementGuid>f9284a3a-9149-499b-8515-fc4d930e02b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'History')]</value>
      <webElementGuid>3483c79a-68fb-4b90-a869-f265b4854cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>e1723a04-13a8-481e-96bd-5e6f6be2b46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team'])[1]/preceding::a[1]</value>
      <webElementGuid>41a51f50-343c-4d27-a457-819861b6be79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/preceding::a[2]</value>
      <webElementGuid>8df6c8f6-c512-4012-956b-ba2b0d2569a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='History']/parent::*</value>
      <webElementGuid>e4138041-6358-41a5-bf65-06dae3fd7e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/view/satisfies/history')]</value>
      <webElementGuid>dc3ff59a-3f91-4e48-a7c9-d2d66466b4e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/a</value>
      <webElementGuid>e49d1e77-37d4-4fb9-946e-478b9541341f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/view/satisfies/history' and (text() = 'History' or . = 'History')]</value>
      <webElementGuid>8d76a3ef-fee6-4c05-83a8-b136cbbd1d1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
