<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_History</name>
   <tag></tag>
   <elementGuidId>3e3bc20a-96b9-40ec-b0a1-d4d7f24ab821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > div.PsKE7e.r8s4j-R6PoUb.IKA38e.baH5ib.oNsfjf > div.I35ICb > a.aJHbb.dk90Ob.hDrhEe.HlqNPb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='yuynLe']/ul/li[2]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;History&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a553fc80-d12e-4ebf-9456-4e0aa7e63160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aJHbb dk90Ob hDrhEe HlqNPb</value>
      <webElementGuid>e5aa7f0c-649b-465f-a4fa-33dedf9433f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>QwLHlb</value>
      <webElementGuid>c6371ee0-7939-4b25-9a0f-bed8f04ba59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>92eeca67-1a0a-4286-977a-b0bd6f03cf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a659734-26d9-4ed2-900a-38368928627d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navtype</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e4b49089-edcf-41f6-9ad9-1914bd539233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/view/satisfies/history</value>
      <webElementGuid>9b5dc200-ada4-47d3-8106-3c02240c16c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/view/satisfies/history</value>
      <webElementGuid>6ed24523-2ca4-4287-a511-f5f7f47485c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fcacdacc-0260-48ec-9f26-56f7a1a62c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c655c600-3f91-4c2f-8a17-cb0928c86c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>History</value>
      <webElementGuid>31993c0c-e060-4f44-a12c-0d48e8f4e55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yuynLe&quot;)/ul[@class=&quot;jYxBte Fpy8Db&quot;]/li[2]/div[@class=&quot;PsKE7e r8s4j-R6PoUb IKA38e baH5ib oNsfjf&quot;]/div[@class=&quot;I35ICb&quot;]/a[@class=&quot;aJHbb dk90Ob hDrhEe HlqNPb&quot;]</value>
      <webElementGuid>38d38a6c-dce7-4cf3-8ea1-18ea30a6a299</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='yuynLe']/ul/li[2]/div/div/a</value>
      <webElementGuid>a44bac85-2bbc-492e-bcad-794ebf54998b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'History')]</value>
      <webElementGuid>8c1ef330-d9af-4158-94a0-1beb1afc4fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>25fa27aa-7ec8-4692-b1db-0e42ba68364b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team'])[1]/preceding::a[1]</value>
      <webElementGuid>fb72f508-2d98-411c-9f55-68f4ac1db5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/preceding::a[2]</value>
      <webElementGuid>1f3492a3-74fc-4e4f-8b7a-a34fd28b982f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='History']/parent::*</value>
      <webElementGuid>42e8d15e-1269-4542-84ff-61b58cce071f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/view/satisfies/history')]</value>
      <webElementGuid>85435e64-5ed5-4d90-be21-a107d40b6434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/a</value>
      <webElementGuid>bd1ca1ac-07b2-4cdf-a4eb-3119d4faec1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/view/satisfies/history' and (text() = 'History' or . = 'History')]</value>
      <webElementGuid>87dd45f4-e0a2-45f6-a949-8b46be0fb36a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
