<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_FAQ_lzy1Td</name>
   <tag></tag>
   <elementGuidId>f690023c-3624-4095-be16-4525ab403cf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.lzy1Td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='atIdViewHeader']/div/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Site home Satisfie's&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ed409f56-855c-4def-b176-1e48962b668d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://lh3.googleusercontent.com/Cp_MXvRzQX839JlkymW51tp7qOrutG2nFCAk5eEtY9LCXpq2Ga2i7rSFq6Lr3VFz6O-JftHDzwoFDfDrpe12zWA=w16383</value>
      <webElementGuid>00831565-1942-4a9c-a4ee-fec1355bb274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lzy1Td</value>
      <webElementGuid>8fb83502-43ac-4030-8afa-5fcf78e60fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>28f4f625-6887-474a-aad5-22670bf41f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Site home</value>
      <webElementGuid>85eeffe4-61a7-4f83-a634-e2389ffd0b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>SwcDWb</value>
      <webElementGuid>ce30dd82-fcf7-481d-8c9a-118f14f8e9d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;atIdViewHeader&quot;)/div[@class=&quot;BbxBP LBrwzc&quot;]/div[@class=&quot;VLoccc QDWEj U8eYrb&quot;]/div[@class=&quot;Pvc6xe&quot;]/div[@class=&quot;TlfmSc YSH9J&quot;]/a[@class=&quot;GAuSPc&quot;]/img[@class=&quot;lzy1Td&quot;]</value>
      <webElementGuid>2a4a20a7-a901-4704-b45b-20eaf084a69b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='atIdViewHeader']/div/div[2]/div/div/a/img</value>
      <webElementGuid>918c55ca-4aff-46ad-9593-2c872e7b856d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://lh3.googleusercontent.com/Cp_MXvRzQX839JlkymW51tp7qOrutG2nFCAk5eEtY9LCXpq2Ga2i7rSFq6Lr3VFz6O-JftHDzwoFDfDrpe12zWA=w16383')])[2]</value>
      <webElementGuid>b6407b3d-485c-4eeb-85f0-0dcbe7731c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>279830e1-e903-4e85-b95e-0f76373d5358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://lh3.googleusercontent.com/Cp_MXvRzQX839JlkymW51tp7qOrutG2nFCAk5eEtY9LCXpq2Ga2i7rSFq6Lr3VFz6O-JftHDzwoFDfDrpe12zWA=w16383']</value>
      <webElementGuid>399700d1-bcb1-4c81-9c85-53617beaa3c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
