<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Team</name>
   <tag></tag>
   <elementGuidId>22ad929d-0b47-4e92-ac45-62221d6a57e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > div.PsKE7e.r8s4j-R6PoUb.IKA38e.baH5ib.oNsfjf > div.I35ICb > a.aJHbb.dk90Ob.hDrhEe.HlqNPb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='yuynLe']/ul/li[3]/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Team&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f60780c7-9ed0-42de-99b4-a476a11602da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aJHbb dk90Ob hDrhEe HlqNPb</value>
      <webElementGuid>9dbfb8e0-876a-4f6e-b668-c4069c3382ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>QwLHlb</value>
      <webElementGuid>2489ba76-bd51-49a0-809a-6eda71e522ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>9f030511-f30b-41f2-b625-40814a9349f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ed57987f-7bd0-4028-aa80-b1cc0f4c4f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navtype</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0013f29f-0b55-46b3-811a-88a0873008d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/view/satisfies/team</value>
      <webElementGuid>a3085bdf-69f2-406b-8f53-1f7af47d4380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/view/satisfies/team</value>
      <webElementGuid>5152a320-7f20-4fa5-90d6-6fe5c23e000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0111af56-9c62-4c25-a6e2-2f6713c0df65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>058102db-11f0-47c1-bfa1-4ed35bbbb877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Team</value>
      <webElementGuid>5b92aa19-77f9-43a4-8a5d-e85f58312873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yuynLe&quot;)/ul[@class=&quot;jYxBte Fpy8Db&quot;]/li[3]/div[@class=&quot;PsKE7e r8s4j-R6PoUb IKA38e baH5ib oNsfjf&quot;]/div[@class=&quot;I35ICb&quot;]/a[@class=&quot;aJHbb dk90Ob hDrhEe HlqNPb&quot;]</value>
      <webElementGuid>ec45a4fc-90fd-4f41-9f08-bb81f33ba176</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='yuynLe']/ul/li[3]/div/div/a</value>
      <webElementGuid>7a8b0ced-955c-4797-8fd5-52d38ced46fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Team')]</value>
      <webElementGuid>f74fc9e6-4bb1-4572-9da1-c4252f49503c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/following::a[1]</value>
      <webElementGuid>5d9dac12-6eff-424f-b136-1b9e3c9ed3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>52463aab-37a0-42a5-a24f-a27f7b86bbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/preceding::a[1]</value>
      <webElementGuid>d4ea9759-3b01-4c67-85c4-954b4becba20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Team']/parent::*</value>
      <webElementGuid>3dcf6145-63ca-4b22-8cda-1b66db1e1ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/view/satisfies/team')]</value>
      <webElementGuid>74c52979-a457-40c6-8b32-8a6a490868af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/a</value>
      <webElementGuid>46103f85-4454-4e82-b991-e22c51f49880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/view/satisfies/team' and (text() = 'Team' or . = 'Team')]</value>
      <webElementGuid>a0e066a0-59d6-4594-8258-c6883fae15b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
