<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Skip to navigation_HBu6N</name>
   <tag></tag>
   <elementGuidId>a5ece004-546b-45fe-bf45-078e49844073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>path.HBu6N</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Show sidebar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>7e31cb3f-46e4-4086-bebd-b226d7ada9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>HBu6N</value>
      <webElementGuid>9e173cef-7905-48ca-82db-5f9e797d444c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M-9 0 L9 0</value>
      <webElementGuid>b37222c4-7404-4d61-9091-dab88e96aa09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>e4471e6c-c2ff-4611-8afe-eb35a21cfe3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4e55b836-de66-45da-901d-33ca3502cc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s9iPrd&quot;)/svg[@class=&quot;wFCWne&quot;]/g[1]/path[@class=&quot;HBu6N&quot;]</value>
      <webElementGuid>19780f5c-108b-4c8a-8c2c-bbccabcdbd7c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
