<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Skip to navigation_HBu6N</name>
   <tag></tag>
   <elementGuidId>fa63f6c6-6093-4468-8301-470950430608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>path.HBu6N</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Show sidebar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>fd92f860-4ea7-4dee-8322-49c2a937af26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>HBu6N</value>
      <webElementGuid>ec08d80e-04aa-401b-b5b1-855dd736b5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M-9 0 L9 0</value>
      <webElementGuid>5aea0c1d-c334-4209-93cc-8c551fb0d3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>a24c7f4b-6ed7-4e15-b71c-54ab59df4eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a9682da2-5fdc-437a-9817-bec8a6ccaa9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s9iPrd&quot;)/svg[@class=&quot;wFCWne&quot;]/g[1]/path[@class=&quot;HBu6N&quot;]</value>
      <webElementGuid>e9413c4a-428b-4236-822b-9533eee68b0f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
